@startuml
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6

Foo2 -> Foo3 : To control
Foo2 -> Foo4 : To entity
Foo2 -> Foo5 : To database
Foo2 -> Foo6 : To collections

@enduml