@startuml
participant СимуляционнаяСистема
participant Агент
participant АлгоритмУправленияВосприятием
participant Сервер

activate Сервер

СимуляционнаяСистема -> Агент: Запуск
activate СимуляционнаяСистема

activate Агент

Агент -> АлгоритмУправленияВосприятием: Запуск
activate АлгоритмУправленияВосприятием

Агент -> Сервер: Действие

Сервер -> АлгоритмУправленияВосприятием: Сенсорная информация

Агент -> Сервер: Действие
Сервер -> АлгоритмУправленияВосприятием: Сенсорная информация
АлгоритмУправленияВосприятием -> Агент: Корректировка параметров

Сервер -> АлгоритмУправленияВосприятием: Сенсорная информация

Агент -> Сервер: Действие
АлгоритмУправленияВосприятием -> Сервер: Изменить направление взгляда

АлгоритмУправленияВосприятием -> Сервер: Повернуть визуальный сенсор
Сервер -> АлгоритмУправленияВосприятием: Сенсорная информация
АлгоритмУправленияВосприятием -> Агент: Корректировка параметров
Агент -> Сервер: Действие
Сервер -> АлгоритмУправленияВосприятием: Сенсорная информация

АлгоритмУправленияВосприятием -> Сервер: Изменить направление взгляда
АлгоритмУправленияВосприятием -> Сервер: Повернуть визуальный сенсор
Сервер -> АлгоритмУправленияВосприятием: Сенсорная информация
АлгоритмУправленияВосприятием -> Агент: Корректировка параметров
АлгоритмУправленияВосприятием -> Агент: Время истекло
destroy АлгоритмУправленияВосприятием
Агент -> Сервер: Действие
Агент -> Сервер: Действие
Агент -> СимуляционнаяСистема: Завершение
deactivate Агент

deactivate СимуляционнаяСистема
@enduml
